version: '2'

networks:
  net_basic:
    external: true

services:
  vehiclelog:
    build: .
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app/vehiclelog
      - /app/vehiclelog/node_modules
      - /app/vehiclelog/creds
    networks:
        - net_basic
