version: '2'

networks:
  net_basic:
    external: true

services:
  fabcar:
    build: .
    environment:
      NODE_ENV: development
    volumes:
      - .:/app/fabcar
      - /app/fabcar/node_modules
      - /app/fabcar/creds
    networks:
        - net_basic
